### ISSUE TITLE
v0.0.3b 预期功能

### ISSUE THREAD

**Issue by NullpointerW** [NullpointerW/AniCat#7]
1.    重构日志库 ✓
2.    ~~cli 订阅时显示步骤流程~~
3.    支持外挂字幕 ✓
4.    全局过滤词 ✓
5.   更完善支持jellyfin✓
6.   通过rss feed订阅 ✓
7.   后台服务运行方式  ✓

**Comment by Goojoe** [comment]
请求加入后台运行服务，可参考DDNS-GO
https://github.com/jeessy2/ddns-go/blob/master/main.go
